# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockScreener', '0003_remove_stock_recommendnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
